global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nasa-app'
    static_configs:
      - targets: ['nasa-app-service:3000']  # Update this line to use the service name and port

