apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nasa-app
      version: v2
  template:
    metadata:
      labels:
        app: nasa-app
        version: v2
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: nasa-app
          image: musthafa110/nasa-app:v2
          ports:
            - containerPort: 3000

