apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-app-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nasa-app
      version: v1
  template:
    metadata:
      labels:
        app: nasa-app
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
        - name: nasa-app
          image: musthafa110/nasa-app:v1
          ports:
            - containerPort: 3000

